import type { Region } from "@/types";

export const REGIONS: Region[] = [
  {
    id: "dutch-north-sea",
    name: "Dutch North Sea",
    nameDutch: "Noordzee (Nederland)",
    lat: 52.8,
    lon: 4.0,
    zoom: 8,
    description: "The Dutch coastal waters of the North Sea, including approaches to IJmuiden, Den Helder and the Hook of Holland.",
    tidalImportance: "high",
    country: ["NL"],
  },
  {
    id: "wadden-sea",
    name: "Wadden Sea",
    nameDutch: "Waddenzee",
    lat: 53.2,
    lon: 5.2,
    zoom: 9,
    description: "The tidal Wadden Sea between the mainland and the West Frisian Islands. Strongly influenced by tides — plan passages carefully.",
    tidalImportance: "high",
    country: ["NL", "DE"],
  },
  {
    id: "ijsselmeer",
    name: "IJsselmeer",
    nameDutch: "IJsselmeer & Markermeer",
    lat: 52.75,
    lon: 5.35,
    zoom: 9,
    description: "The largest lake in the Netherlands. No tidal influence but can produce steep, short waves in strong winds.",
    tidalImportance: "low",
    country: ["NL"],
  },
  {
    id: "english-channel",
    name: "English Channel",
    nameDutch: "Het Kanaal",
    lat: 50.6,
    lon: 0.5,
    zoom: 7,
    description: "The busiest shipping lane in the world. Strong tidal streams, variable weather and high traffic density.",
    tidalImportance: "high",
    country: ["GB", "FR", "BE", "NL"],
  },
  {
    id: "north-sea-central",
    name: "Central North Sea",
    nameDutch: "Centrale Noordzee",
    lat: 56.0,
    lon: 3.5,
    zoom: 7,
    description: "Open North Sea passages — UK east coast to Denmark / Norway. Often rough with significant swell.",
    tidalImportance: "medium",
    country: ["GB", "DK", "NO", "NL"],
  },
  {
    id: "skagerrak-kattegat",
    name: "Skagerrak & Kattegat",
    nameDutch: "Skagerrak / Kattegat",
    lat: 57.5,
    lon: 10.5,
    zoom: 7,
    description: "Scandinavian waters between Denmark, Norway and Sweden. Gateway to the Baltic.",
    tidalImportance: "medium",
    country: ["DK", "NO", "SE"],
  },
  {
    id: "baltic-west",
    name: "Western Baltic",
    nameDutch: "Westelijke Oostzee",
    lat: 55.5,
    lon: 14.0,
    zoom: 7,
    description: "The western Baltic including the German Bight, Danish straits and Bornholm. Lower salinity and limited tidal range.",
    tidalImportance: "low",
    country: ["DE", "DK", "SE", "PL"],
  },
  {
    id: "irish-sea",
    name: "Irish Sea",
    nameDutch: "Ierse Zee",
    lat: 53.5,
    lon: -4.5,
    zoom: 7,
    description: "Between Ireland and Great Britain. Strong tidal streams particularly around headlands.",
    tidalImportance: "high",
    country: ["IE", "GB"],
  },
  {
    id: "bay-of-biscay",
    name: "Bay of Biscay",
    nameDutch: "Golf van Biskaje",
    lat: 46.0,
    lon: -4.0,
    zoom: 6,
    description: "Notorious for large Atlantic swells and rapidly developing depressions. Respect the forecasts here.",
    tidalImportance: "medium",
    country: ["FR", "ES"],
  },
  {
    id: "mediterranean-west",
    name: "Western Mediterranean",
    nameDutch: "Westelijke Middellandse Zee",
    lat: 40.5,
    lon: 4.5,
    zoom: 6,
    description: "The western Med including the Balearics, French Riviera, Corsica and Sardinia. Watch for Tramontane and Mistral.",
    tidalImportance: "low",
    country: ["ES", "FR", "IT"],
  },
];

export function getRegion(id: string): Region | undefined {
  return REGIONS.find((r) => r.id === id);
}

export function getDefaultRegion(): Region {
  return REGIONS[0];
}
